import os
import sys
import time
run = True
os.system ("clear")
print ("-----------------------------------")
print ("/                                 /")
print ("/  Insert file name + extension:  /")
print ("/                                 /")
print ("-----------------------------------")
print ("")
file_name = input ("> ")
os.system ("clear")
print ("---------------------")
print ("/                   /")
print ("/  Insert content:  /")
print ("/                   /")
print ("---------------------")
print ("")
file_content = input ("> ")
os.system ("clear")
print ("----------------------------")
print ("/                          /")
print ("/  WRITING IN PROGRESS.    /")
print ("/                          /")
print ("----------------------------")
print ("")
print ("-------------------------------")
print ("/  #######              / 33% /")
print ("-------------------------------")
time.sleep (0.5)
os.system ("clear")
file = open (file_name, "w")
print ("----------------------------")
print ("/                          /")
print ("/  WRITING IN PROGRESS..   /")
print ("/                          /")
print ("----------------------------")
print ("")
print ("-------------------------------")
print ("/ ##############        / 66% /")
print ("-------------------------------")
time.sleep (0.5)
os.system ("clear")
file.write (file_content)
print ("----------------------------")
print ("/                          /")
print ("/  WRITING IN PROGRESS...  /")
print ("/                          /")
print ("----------------------------")
print ("")
print ("-------------------------------")
print ("/ ##################### / 99% /")
print ("-------------------------------")
time.sleep (0.5)
os.system ("clear")
print ("-------------------------------------")
print ("/                                   /")
print ("/  WRITING COMPLETED SUCCESSFULLY!  /")
print ("/                                   /")
print ("-------------------------------------")
time.sleep (5)
os.system ("clear")
