import os
import sys
import time
run = True
os.system ("clear")
print ("---------------------------------------")
print ("/                                     /")
print ("/  Inserisci nome file + estensione:  /")
print ("/                                     /")
print ("---------------------------------------")
print ("")
file_name = input ("> ")
os.system ("clear")
print ("--------------------------")
print ("/                        /")
print ("/  Inserisci contenuto:  /")
print ("/                        /")
print ("--------------------------")
print ("")
file_content = input ("> ")
os.system ("clear")
print ("---------------------------")
print ("/                         /")
print ("/  SCRITTURA IN CORSO.    /")
print ("/                         /")
print ("---------------------------")
print ("")
print ("-------------------------------")
print ("/  #######              / 33% /")
print ("-------------------------------")
time.sleep (0.5)
os.system ("clear")
file = open (file_name, "w")
print ("---------------------------")
print ("/                         /")
print ("/  SCRITTURA IN CORSO..   /")
print ("/                         /")
print ("---------------------------")
print ("")
print ("-------------------------------")
print ("/ ##############        / 66% /")
print ("-------------------------------")
time.sleep (0.5)
os.system ("clear")
file.write (file_content)
print ("---------------------------")
print ("/                         /")
print ("/  SCRITTURA IN CORSO...  /")
print ("/                         /")
print ("---------------------------")
print ("")
print ("-------------------------------")
print ("/ ##################### / 99% /")
print ("-------------------------------")
time.sleep (0.5)
os.system ("clear")
print ("----------------------------------------")
print ("/                                      /")
print ("/  SCRITTURA EFFETTUATA CON SUCCESSO!  /")
print ("/                                      /")
print ("----------------------------------------")
time.sleep (5)
os.system ("clear")
